include("multiplay/script/mods/SaveLoad.js");
include("multiplay/script/mods/Template.js");
include("multiplay/script/mods/tools.js");
include("multiplay/script/mods/Spawner.js");
include("multiplay/script/mods/Scavengers.js");
include("multiplay/script/mods/towerDefense.js");
include("multiplay/script/mods/configAPI.js");
include("multiplay/script/mods/configReader.js");
include("config.js");
